jobs:
  run_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ matrix.rev }}-${{ hashFiles('todays-date') }}
          path: _neovim
      - name: Prepare
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.rev }}" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            rev: nightly/nvim-linux64.tar.gz
          - os: ubuntu-22.04
            rev: v0.7.2/nvim-linux64.tar.gz
          - os: ubuntu-22.04
            rev: v0.8.2/nvim-linux64.tar.gz
name: Test
on:
  pull_request:
    paths:
      - "lua/**"
      - "plugin/**"
      - "script/*"
      - "makefile"
  push:
    paths:
      - "lua/**"
      - "plugin/**"
      - "script/*"
      - "makefile"
